export default {
  issues: "/issues",
  bet: "/bet",
  captcha: "/captcha",
  login: "/login",
  register: "/register",
  logout: "/logout",
  userInfo: "/userInfo",
  updatePassword: "/updatePassword",
  updateTradePassword: "/updateTradePassword",
  addTradePassword: "/addTradePassword",
  addCard: "/addCard",
  delCard: "/delCard",
  cards: "/cards",
  orders: "/orders",
  withdraw: "/withdraw",
  withdraws: "/withdraws",
  recharges: "/recharges",
  bills: "/bills",
  carousels: "/carousels",
  platforms: "/platforms",
  configs: "/configs",
  rooms: "/rooms",
  updateUserInfo: "/updateUserInfo"
};
